services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  mysql:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=ubidict'
      - 'MYSQL_PASSWORD=ubidict'
      - 'MYSQL_ROOT_PASSWORD=ubidict'
      - 'MYSQL_USER=ubidict'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
